-- Normalized profile roles: up to 2 roles per jammer with per-role experience level.

CREATE TABLE IF NOT EXISTS public.profile_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  role text NOT NULL,
  experience_level text NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT profile_roles_user_role_unique UNIQUE (user_id, role),
  CONSTRAINT profile_roles_role_check CHECK (
    role IN ('developer', '2d-artist', '3d-artist', 'audio', 'voice_actor', 'writer', 'game-design', 'ui-ux', 'qa')
  ),
  CONSTRAINT profile_roles_experience_level_check CHECK (
    experience_level IN ('beginner', 'junior', 'regular', 'advanced', 'senior', 'veteran')
  )
);

CREATE INDEX IF NOT EXISTS idx_profile_roles_user_id ON public.profile_roles(user_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_profile_roles_single_primary
  ON public.profile_roles(user_id)
  WHERE is_primary = true;

CREATE OR REPLACE FUNCTION public.profile_roles_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS profile_roles_updated_at_trigger ON public.profile_roles;
CREATE TRIGGER profile_roles_updated_at_trigger
  BEFORE UPDATE ON public.profile_roles
  FOR EACH ROW
  EXECUTE FUNCTION public.profile_roles_updated_at();

-- Enforce max 2 roles per jammer.
CREATE OR REPLACE FUNCTION public.profile_roles_enforce_max_two()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  role_count integer;
BEGIN
  SELECT COUNT(*) INTO role_count
  FROM public.profile_roles
  WHERE user_id = NEW.user_id
    AND (TG_OP <> 'UPDATE' OR id <> NEW.id);

  IF role_count >= 2 THEN
    RAISE EXCEPTION 'A jammer can only have up to 2 roles.';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS profile_roles_enforce_max_two_trigger ON public.profile_roles;
CREATE TRIGGER profile_roles_enforce_max_two_trigger
  BEFORE INSERT OR UPDATE ON public.profile_roles
  FOR EACH ROW
  EXECUTE FUNCTION public.profile_roles_enforce_max_two();

ALTER TABLE public.profile_roles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profile_roles_select_all" ON public.profile_roles;
DROP POLICY IF EXISTS "profile_roles_insert_own" ON public.profile_roles;
DROP POLICY IF EXISTS "profile_roles_update_own" ON public.profile_roles;
DROP POLICY IF EXISTS "profile_roles_delete_own" ON public.profile_roles;

CREATE POLICY "profile_roles_select_all"
  ON public.profile_roles
  FOR SELECT
  USING (true);

CREATE POLICY "profile_roles_insert_own"
  ON public.profile_roles
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "profile_roles_update_own"
  ON public.profile_roles
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "profile_roles_delete_own"
  ON public.profile_roles
  FOR DELETE
  USING (auth.uid() = user_id);

WITH normalized_profiles AS (
  SELECT
    p.id AS user_id,
    NULLIF(LOWER(TRIM(p.main_role)), '') AS main_role_key,
    NULLIF(LOWER(TRIM(p.default_role)), '') AS default_role_key,
    NULLIF(LOWER(TRIM(p.role)), '') AS role_key,
    CASE
      WHEN LOWER(TRIM(COALESCE(p.experience_level, p.experience, ''))) = 'hobbyist' THEN 'junior'
      WHEN LOWER(TRIM(COALESCE(p.experience_level, p.experience, ''))) = 'confirmed' THEN 'regular'
      WHEN LOWER(TRIM(COALESCE(p.experience_level, p.experience, ''))) = 'expert' THEN 'senior'
      WHEN LOWER(TRIM(COALESCE(p.experience_level, p.experience, ''))) IN ('beginner', 'junior', 'regular', 'advanced', 'senior', 'veteran')
        THEN LOWER(TRIM(COALESCE(p.experience_level, p.experience)))
      ELSE 'regular'
    END AS normalized_experience
  FROM public.profiles p
),
role_candidates AS (
  SELECT
    user_id,
    role,
    normalized_experience,
    is_primary,
    priority
  FROM (
    SELECT user_id, main_role_key AS role, normalized_experience, true AS is_primary, 1 AS priority
    FROM normalized_profiles
    WHERE main_role_key IS NOT NULL

    UNION ALL

    SELECT user_id, default_role_key AS role, normalized_experience, true AS is_primary, 2 AS priority
    FROM normalized_profiles
    WHERE default_role_key IS NOT NULL
      AND default_role_key <> main_role_key

    UNION ALL

    SELECT user_id, role_key AS role, normalized_experience, true AS is_primary, 3 AS priority
    FROM normalized_profiles
    WHERE role_key IS NOT NULL
      AND role_key <> main_role_key
      AND role_key <> default_role_key

    UNION ALL

    SELECT user_id, default_role_key AS role, normalized_experience, false AS is_primary, 4 AS priority
    FROM normalized_profiles
    WHERE default_role_key IS NOT NULL
      AND main_role_key IS NOT NULL
      AND default_role_key <> main_role_key

    UNION ALL

    SELECT user_id, role_key AS role, normalized_experience, false AS is_primary, 5 AS priority
    FROM normalized_profiles
    WHERE role_key IS NOT NULL
      AND main_role_key IS NOT NULL
      AND role_key <> main_role_key
      AND role_key <> default_role_key
  ) source
),
deduplicated AS (
  SELECT DISTINCT ON (user_id, role)
    user_id,
    role,
    normalized_experience,
    is_primary,
    priority
  FROM role_candidates
  ORDER BY user_id, role, priority
),
ranked_candidates AS (
  SELECT
    user_id,
    role,
    normalized_experience,
    is_primary,
    ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY priority ASC) AS position
  FROM deduplicated
)
INSERT INTO public.profile_roles (user_id, role, experience_level, is_primary)
SELECT
  user_id,
  role,
  normalized_experience,
  CASE WHEN position = 1 THEN true ELSE false END AS is_primary
FROM ranked_candidates
WHERE role IN ('developer', '2d-artist', '3d-artist', 'audio', 'voice_actor', 'writer', 'game-design', 'ui-ux', 'qa')
  AND position <= 2
ON CONFLICT (user_id, role) DO NOTHING;
